FORMAT: 1A

# La API de Harry Potter
API de Harry Potter para la comunidad de PUNCH 🔥

#Group Casas
Recurso de casas disponibles

## Todas las casas [/api/houses]
### Todas las casas [GET]

+ Response 200 (application/json)
    {
        info : {count : Number, next : String | null, prev : String | null},
        data : [
            {
                _id : ObjectId,
                name : String,
                headMaster : String,
                ghost : String,
                ghostNickName : String,
                shield : String,
                hymn : String,
                thumbnail : String,
                colors : Array,
                animal : String,
                commonRoom : String,
                founder : String,
                history : String,
            }
        ]
    }
## Mostrar una casa especifica [/api/houses/single/:id]
### Mostrar una casa especifica [GET]

+ Response 200 (application/json)
    {
            _id : ObjectId,
            name : String,
            headMaster : String,
            ghost : String,
            ghostNickName : String,
            shield : String,
            hymn : String,
            thumbnail : String,
            colors : Array,
            animal : String,
            commonRoom : String,
            founder : String,
            history : String,
    }

#Group Hechizos
Recurso de hechizos disponibles

## Todos los hechizos [/api/spells]
### Todos los hechizos [GET]

+ Response 200 (application/json)
    {
        info : {count : Number, next : String | null, prev : String | null},
        data : [
            {
                _id : ObjectId,
               








            }
        ]
    }

## Mostrar un hechizo específico [/api/spells/single/:id]
### Mostrar un hechizo específico [GET]

+ Response 200 (application/json)
    {
            _id : ObjectId,
           








           
    }